version: '3.9'

services:

  postgresql13:
    container_name: postgresql13
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: America/Sao_Paulo
