version: '3.9'

services:

  postgresql_poc_test:
    container_name: postgresql_poc_test
    build:
      context: ./data/src/test/resources/docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: America/Sao_Paulo

  redis_poc_test:
    container_name: redis_poc_test
    image: redis:6.2.6
    ports:
      - "6379:6379"
    environment:
      TZ: America/Sao_Paulo
