version: '3.9'

services:

  postgresql13:
    container_name: postgresql13
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: America/Sao_Paulo

  redis:
    container_name: redis
    image: redis:6.2.6
    ports:
      - "6379:6379"
    environment:
      TZ: America/Sao_Paulo
